refactor: add docker
Sherstyankin/java-shareit pull request #6
Opened 2023-07-03 15:09 UTC by Sherstyankin

2023-07-04 16:50 UTC, db-exp requested changes

2023-07-04 16:50 UTC, db-exp commented on server/src/test/java/ru/practicum/shareit/item/ItemServiceImplTest.java
>      void addComment_whenInvokedNotValid_thenReturnUserNotBookerOrBookingNotFinishedException() {
Предлагаю придерживаться camelCase нотации даже в тестах. В Java snake_case не рекомендуется использовать

2023-07-04 16:50 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        checkIsUserExists(userId);
кажется, что если того не требуют тесты postman, то проверять существование пользователя излишне

2023-07-04 16:50 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        checkIsUserExists(userId);
ниже есть findUser с похожей логикой - тут не стоит проверять еще раз

2023-07-04 16:50 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        checkIsUserExists(userId);
ниже идет проверка на владельца, тут тоже не стоит проверять на существование

2023-07-04 16:50 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        checkIsUserExists(userId);
можно не проверять - ниже по коду либо вернется пустота, либо отпадет на проверке владельца

2023-07-04 16:50 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        checkIsUserExists(userId);
можно заменить на findUser - логика одинаковая

2023-07-04 16:50 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    private void checkIsUserExists(Long userId) {
предлагаю метод удалить и использовать findUser из этого класса, ну или наоборот)

2023-07-04 16:50 UTC, db-exp commented on pom.xml
> +    <dependencies>
в родительском pom'е все   <dependencies> стоит превратить в dependencyManagement, если хочется версии зависимостей указывать один раз тут, просто блок dependecies тут держать не стоит

2023-07-04 16:50 UTC, db-exp commented on server/src/main/resources/application.properties
> +#spring.datasource.url=jdbc:h2:mem:testdb
лучше удалять такой код, а для разделения тест/сборка/локально использовать профили

2023-07-04 16:50 UTC, db-exp commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/BookingState.java
> +        for (BookingState state : values()) {
еще как вариант - BookingState.valueOf(stringState.toUpperCase())

2023-07-05 06:25 UTC, Sherstyankin commented on server/src/test/java/ru/practicum/shareit/item/ItemServiceImplTest.java
>      void addComment_whenInvokedNotValid_thenReturnUserNotBookerOrBookingNotFinishedException() {
Поменял на snake_case, так как в хард вебинаре предлагали именно такой вариант наименования тестов.

2023-07-05 06:37 UTC, Sherstyankin commented on server/src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        checkIsUserExists(userId);
Посчитал, что доп проверка лишней не будет, тем более постман не проверяет.

2023-07-05 06:41 UTC, Sherstyankin commented on server/src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        checkIsUserExists(userId);
Изначально использовал findUser и для получения и для проверки. Но предыдущий ревьюер порекомендовал вынести проверку в отдельный метод с применением метода `existsById `

2023-07-05 06:56 UTC, Sherstyankin commented on server/src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        checkIsUserExists(userId);
Согласен, избыточна.

2023-07-05 09:18 UTC, Sherstyankin commented on server/src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        checkIsUserExists(userId);
Исправил.

2023-07-05 09:43 UTC, Sherstyankin commented on server/src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        checkIsUserExists(userId);
Изначально использовал findUser и для получения и для проверки. Но предыдущий ревьюер порекомендовал вынести проверку в отдельный метод с применением метода `existsById ` .

2023-07-05 09:43 UTC, Sherstyankin commented on server/src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    private void checkIsUserExists(Long userId) {
Изначально использовал findUser и для получения и для проверки. Но предыдущий ревьюер порекомендовал вынести проверку в отдельный метод с применением метода `existsById ` .

2023-07-05 10:28 UTC, Sherstyankin commented on pom.xml
> +    <dependencies>
Вообще удалил все зависимоти из родительского pom, так как увидел, что они дублируются в дочерних)

2023-07-05 10:50 UTC, Sherstyankin commented on server/src/main/resources/application.properties
> +#spring.datasource.url=jdbc:h2:mem:testdb
Убрал лишнее. Но с профилями пока не разобрался.

2023-07-05 11:54 UTC, Sherstyankin commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/BookingState.java
> +        for (BookingState state : values()) {
Применил)

2023-07-05 12:58 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    private void checkIsUserExists(Long userId) {
Тогда проблема в том, что findUser и existsById дублируют логику, можно findUserById сделать и будет хорошо

2023-07-05 12:59 UTC, db-exp commented on server/src/test/java/ru/practicum/shareit/item/ItemServiceImplTest.java
>      void addComment_whenInvokedNotValid_thenReturnUserNotBookerOrBookingNotFinishedException() {
Печаль) скоро в java как на python писать будем

2023-07-05 14:28 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    private void checkIsUserExists(Long userId) {
Я предлагаю - переименовать findUser на findUserById, а checkIsUserExists просто удалить
В принципе - не крит и можно просто учитывать такие вещи в будущих работах

2023-07-05 14:28 UTC, db-exp approved these changes

2023-07-05 15:29 UTC, merged